---
- hosts: localhost
  vars:
    package_list:
      - bat
      - curl
      - distrobox
      - fd-find
      - fzf
      - gh
      - git-delta
      - gitui
      - helix
      - jq
      - lsd
      - meld
      - podman
      - podman-compose
      - podman-docker
      - ripgrep
      - stow
      - tealdeer
      - tmux
      - tree
      - zoxide
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    repo_removed_list:
      - rpmfusion-nonfree-nvidia-driver
      - rpmfusion-nonfree-nvidia-driver-debuginfo
      - rpmfusion-nonfree-nvidia-driver-source

    rpm_fusion_free: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    rpm_fusion_nonfree: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
  
  tasks:
  - name: Remove some repositories
    yum_repository:
      name: "{{ item }}"
      state: absent
      file: rpmfusion-nonfree-nvidia-driver
    loop: "{{ repo_removed_list }}"

  - name: Install RPM Fusion repositories
    ansible.builtin.dnf:
      name: 
        - "{{ rpm_fusion_free }}"
        - "{{ rpm_fusion_nonfree }}"
      state: present
      disable_gpg_check: true
      
    
  - name: Install base packages
    dnf:
      name: "{{ package_list }}"
      state: latest

  - name: Enable COPR for starship prompt
    community.general.copr:
      name: atim/starship
      state: enabled

  - name: Install starship prompt
    dnf:
      name: starship
      state: latest
