---
- hosts: localhost
  vars:
    flatpak_list:
      - md.obsidian.Obsidian
      - com.discordapp.Discord
      - com.spotify.Client
      - com.github.tchx84.Flatseal
      - com.mattjakeman.ExtensionManager
      - com.bitwarden.desktop
      - com.github.GradienceTeam.Gradience
      
    package_list:
      - adw-gtk3-theme
      - bat
      - curl
      - distrobox
      - fd-find
      - fzf
      - gh
      - git-delta
      - gitui
      - helix
      - jq
      - lsd
      - meld
      - podman
      - podman-compose
      - podman-docker
      - ripgrep
      - stow
      - tealdeer
      - tmux
      - tree
      - zoxide
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    repo_removed_list:
      - rpmfusion-nonfree-nvidia-driver
      - rpmfusion-nonfree-nvidia-driver-debuginfo
      - rpmfusion-nonfree-nvidia-driver-source

    rpm_fusion_free: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    rpm_fusion_nonfree: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
  
  tasks:
  - name: Remove some repositories
    ansible.builtin.yum_repository:
      name: "{{ item }}"
      state: absent
      file: rpmfusion-nonfree-nvidia-driver
    loop: "{{ repo_removed_list }}"

  - name: Install RPM Fusion repositories
    ansible.builtin.dnf:
      name: 
        - "{{ rpm_fusion_free }}"
        - "{{ rpm_fusion_nonfree }}"
      state: present
      disable_gpg_check: true
      
    
  - name: Install base packages
    ansible.builtin.dnf:
      name: "{{ package_list }}"
      state: latest

  - name: Enable COPR for starship prompt
    community.general.copr:
      name: atim/starship
      state: enabled

  - name: Install starship prompt
    ansible.builtin.dnf:
      name: starship
      state: latest

  - name: Install Gnome Extensions
    ansible.builtin.dnf:
      name:
      - gnome-shell-extension-common
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-forge
      state: latest

  - name: Install some flatpak software
    community.general.flatpak:
      name: "{{ flatpak_list }}"
      state: present
    
  - name: Install VSCode RPM key
    ansible.builtin.rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Configure VSCode repository
    ansible.builtin.yum_repository:
      name: visual-studio-code 
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      enabled: true
      gpgcheck: true
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      file: vscode

  - name: Install VSCode
    ansible.builtin.dnf:
      name: code
      state: latest
      update_cache: true
